name: news_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  lottie: ^2.6.0
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  flextras: ^1.0.0
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  cached_network_image: ^3.3.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

